#!/bin/bash

sudo usermod -a -G plugdev $USER

sudo cat <<\EOF >/etc/udev/rules.d/99-hidraw.rules
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0660", GROUP="plugdev"
EOF

echo "Installing mppsolar package with pip..."
sudo apt update
sudo apt install python3-pip python3-dev
sudo pip install mppsolar
sudo apt install libglib2.0-dev
sudo pip install systemd-python

sleep 3
echo "Creating /etc/mpp-solar/mpp-solar.conf"
echo "Please modify /etc/mpp-solar/mpp-solar.conf"
sleep 3

sudo mkdir -p /etc/mpp-solar
sudo chmod 777 /etc/mpp-solar

sudo cat <<\EOF >/etc/mpp-solar/mpp-solar.conf
[SETUP]
# Number of seconds to pause between command execution loop
# 0 is no pause, greater than 60 will cause service restarts
pause=5
mqtt_broker=192.168.0.100
mqtt_user=user
mqtt_pass=pass

# This example would work on a single LV5048
[Inverter1_LV5048]
protocol=PI41
port=/dev/hidraw0
baud=2400
command=QPGS0,QP2GS0
tag=LV5048
outputs=hass_mqtt
EOF

sleep 3
echo "Creating /etc/systemd/user/mpp-solar.service"
echo "Please modify /etc/systemd/user/mpp-solar.service"
sleep 3

sudo cat <<\EOF >/etc/systemd/user/mpp-solar.service

# systemd unit file for the MPP-Solar Service
#
# needs to go to /etc/systemd/user/*

[Unit]
# Human readable name of the unit
Description=MPP Solar Service


[Service]
# Command to execute when the service is started
ExecStart=/usr/bin/python3 /usr/local/bin/mpp-solar -C /etc/mpp-solar/mpp-solar.conf --daemon

# Disable Python's buffering of STDOUT and STDERR, so that output from the
# service shows up immediately in systemd's logs
Environment=PYTHONUNBUFFERED=1

# Automatically restart the service if it crashes
Restart=always
WatchdogSec=300

# Our service will notify systemd once it is up and running
Type=notify

# Use a dedicated user to run our service
# User=mpp_service


[Install]
# Tell systemd to automatically start this service when the system boots
# (assuming the service is enabled)
WantedBy=default.target
EOF

sleep 3
systemctl --user list-unit-files|grep mpp-solar
sleep 3
systemctl --user start mpp-solar
sleep 3
systemctl --user enable mpp-solar
sleep 3
sudo loginctl enable-linger $USER
sleep 3
systemctl --user list-unit-files | grep mpp-solar


