#!/bin/bash
echo "Adding /bin to PATH"
# sleep 1
echo "export PATH="\$HOME/.local/bin:\$PATH"" >> ~/.bashrc
echo "..."
echo "Starting mpp-solar-commands setup...
echo "Copying /bin to ~/.local/bin
mkdir ~/.local/bin/
cp -r bin/* ~/.local/bin/
sleep 1
echo "IMPORTANT STEPS:"
echo "Copying files inside etc directory to the /etc directory in the host"
sudo cp -r etc/* /etc/
# reloading systemd daemon to get our service file
sudo systemctl daemon-reload
echo "Please use command source ~/.bashrc to apply PATH changes immediately"
echo "Below for copy > paste"
echo "source ~/.bashrc"
