#!/bin/bash
echo "PCP<NN>: Setting Inverter charger priority"
echo "00 - utility first"
echo "01 - solar first"
echo "02 - solar and utility"
echo "03 - only solar"
echo

read -n 1 -p "Inverter selection:" inverter
read -n 2 -p "Selection:" value

function command () {
    mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP$value;
    }
command $value
