#!/bin/bash
echo "MNCHGC<nnn>: Setting max charging current"
echo "nnn is max charging current"
echo "...060,070,080,090..."

read -p Selection: value

function command () {
    mpp-solar -p /dev/hidraw0 -P PI41 -c MNCHGC0$value;
    }
command $value
