#!/bin/bash

echo "Select an option:"
echo "1. Inverter input change"
echo "2. Option 2"
echo "3. Option 3"

read choice

case $choice in
    1)
        echo "Inverter input"

        echo
        read -n 1 -p "Selection:" inverter

        echo "PCP<NN>: Setting Inverter charger priority"
        echo "00 - utility first"
        echo "01 - solar first"
        echo "02 - solar and utility"
        echo "03 - only solar"

        read -n 2 -p "Selection:" value

        function command () {
            mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP$value;
            }
        command $inverter $value
        ;;
    2)
        echo "You selected option 2."
        ;;
    3)
        echo "You selected option 3."
        ;;
    *)
        echo "Invalid choice."
        ;;
esac



