#!/bin/bash
echo "MUCHGC<nnn>: Setting utility max charging current"
echo "nnn is max charging current"
echo "010,020,030,040..."

read -p Selection: value

function command () {
    mpp-solar -p /dev/hidraw0 -P PI41 -c MUCHGC$value;
    }
command $value
