#!/bin/bash
echo "PBFT<nn.n>: Setting battery float charging voltage"
echo "nn.n: 48.0V ~ 58.4V"
echo

read -n 2 -p "Selection:" value

function command () {
    mpp-solar -p /dev/hidraw0 -P PI41 -c PBFT$value;
    }
command $value
