#!/bin/bash
echo "PBCV<nn.n><cr>: Set battery re-charge voltage"
echo "nn.n: 44V/45V/46V/47V/48V/49V/50V/51V"

read -p Selection: value

function command () {
    mpp-solar -p /dev/hidraw0 -P PI41 -c PBCV$value;
    }
command $value
