#!/bin/bash
echo "PCVV<nn.n>: Setting battery C.V. (constant voltage) charging voltage"
echo "nn.n: 48.0V ~ 58.4V"

read -p Selection: value

function command () {
    mpp-solar -p /dev/hidraw0 -P PI41 -c PCVV$value;
    }
command $value
