#!/bin/bash

# Default values
inverter=""
change=""
option=""

# Function to display usage
function usage {
    echo
    echo "Usage: msc [-i <inverter>] [-c <change>] [-o <option>] [-h]"
    echo "Options:"
    echo "  -i <inverter>  Specify the inverter: 0=casa|2=aires "
    echo "  -c <change>    Specify the change: i=input|o=output"
    echo "  -o <option>    Specify the option: s=solar|u=utility"
    echo "  -h             Display this help message"
    echo
    exit 1
}

# Parse command line options
while getopts ":i:c:o:h" opt; do
    case ${opt} in
        i)
            inverter=$OPTARG
            ;;
        c)
            change=$OPTARG
            ;;
        o)
            option=$OPTARG
            ;;
        h)
            usage
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument."
            usage
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG."
            usage
            ;;
    esac
done

# Check if all three options were provided
if [ -z "$inverter" ] || [ -z "$change" ] || [ -z "$option" ]; then
    echo "Error: All options (-i, -c, -o) must be provided."
    usage
fi

# echo "Inverter: $inverter"
# echo "change: $change"
# echo "Option: $option"

case $change in
    i)
        case $option in
            s)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP03;
                    }
                command $inverter
                echo
                echo "Inverter changing to Only Solar charge"
                echo
              ;;
            u)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP02;
                    }
                command $inverter
                echo
                echo "Inverter changing to Solar and Utility charge"
                echo
              ;;
        esac
        ;;
    o)
        case $option in
            s)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c POP02;
                    }
                command $inverter
                echo
                echo "Inverter changing to Solar output"
                echo
              ;;
            u)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c POP00;
                    }
                command $inverter
                echo
                echo "Inverter changing to Utility output"
                echo
              ;;
        esac
        ;;
    h)
        usage
        ;;
    *)
        echo "Invalid choice."
        ;;
esac
