#!/bin/bash

# Default values
inverter=""
change=""
option=""

# Function to display usage
function usage {
    echo
    echo "Usage: msc-next [-i <inverter>] [-c <change>] [-o <option>] [-h]"
    echo "Options:"
    echo "  -i <inverter>  Specify the inverter: 0=casa|2=aires "
    echo "  -c <change>    Specify the change: i=input|o=output"
    echo "  -o <option>    Specify the option: s=solar|u=utility"
    echo "  -h             Display this help message"
    echo
    exit 1
}

# Parse command line options
while getopts ":i:in:o:h" opt; do
    case ${opt} in
        i)
            inverter=$OPTARG
            ;;
        c)
            change=$OPTARG
            ;;
        o)
            option=$OPTARG
            ;;
        h)
            usage
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument."
            usage
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG."
            usage
            ;;
    esac
done

# Check if all three options were provided
if [ -z "$inverter" ] || [ -z "$change" ] || [ -z "$option" ]; then
    echo "Error: All options (-i, -c, -o) must be provided."
    usage
fi

# echo "Inverter: $inverter"
# echo "change: $change"
# echo "Option: $option"

case $change in
    i)
        case $option in
            s)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP03;
                    }
                command $inverter
                echo
              ;;
            u)
                function command () {
                    mpp-solar -p /dev/hidraw$inverter -P PI41 -c PCP02;
                    }
                command $inverter
                echo
              ;;
        esac
        ;;
    o)
        echo
        echo "POP<NN>: Setting Inverter output source priority"
        echo "00 - utility first"
        echo "01 - solar first"
        echo "02 - SBU priority"
        echo

        read -n 2 -p "Selection:" value

        function command () {
            mpp-solar -p /dev/hidraw$inverter -P PI41 -c POP$value;
            }
        command $inverter $value
        ;;
    3)
        echo
        echo "Show inverter data - PLEASE SELECT"
        echo "QPIRI - Current Settings inquiry for LV5048"
        echo "QFLAG - Flag Status inquiry"
        echo "QPIGS - General Status Parameters inquiry LV5048"
        echo "QMOD - Inverter Mode inquiry"
        echo "QPIWS - Warning status inquiry"
        echo 

        read -n 2 -p "Selection:" value

        

        function command () {
            mpp-solar -p /dev/hidraw$inverter -P PI41 -c $value;
            }
        command $inverter $value
        ;;
    h)
        usage
        ;;
    *)
        echo "Invalid choice."
        ;;
esac
