#!/bin/bash

# Default values
inverter=""
input=""
option=""

# Function to display usage
function usage {
    echo "Usage: msc-next [-i <inverter>] [-in <input>] [-o <option>] [-h]"
    echo "Options:"
    echo "  -i <inverter>  Specify the inverter"
    echo "  -in <input>    Specify the input"
    echo "  -o <option>    Specify the option"
    echo "  -h             Display this help message"
    exit 1
}

# Parse command line options
while getopts ":i:in:o:h" opt; do
    case ${opt} in
        i)
            inverter=$OPTARG
            ;;
        in)
            input=$OPTARG
            ;;
        o)
            option=$OPTARG
            ;;
        h)
            usage
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument."
            usage
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG."
            usage
            ;;
    esac
done

# Check if all three options were provided
if [ -z "$inverter" ] || [ -z "$input" ] || [ -z "$option" ]; then
    echo "Error: All options (-i, -in, -o) must be provided."
    usage
fi

echo "Inverter: $inverter"
echo "Input: $input"
echo "Option: $option"

# Rest of your script...
