#!/bin/bash

# Default values
inverter=""
change=""
option=""

# Function to display usage
function usage {
    echo "Usage: msc-next [-i <inverter>] [-c <change>] [-o <option>] [-h]"
    echo "Options:"
    echo "  -i <inverter>  Specify the inverter: 0=casa / 2=aires "
    echo "  -c <change>    Specify the change: i=input / o=output"
    echo "  -o <option>    Specify the option"
    echo "  -h             Display this help message"
    exit 1
}

# Parse command line options
while getopts ":i:in:o:h" opt; do
    case ${opt} in
        i)
            inverter=$OPTARG
            ;;
        in)
            change=$OPTARG
            ;;
        o)
            option=$OPTARG
            ;;
        h)
            usage
            ;;
        :)
            echo "Error: Option -$OPTARG requires an argument."
            usage
            ;;
        \?)
            echo "Error: Invalid option -$OPTARG."
            usage
            ;;
    esac
done

# Check if all three options were provided
if [ -z "$inverter" ] || [ -z "$change" ] || [ -z "$option" ]; then
    echo "Error: All options (-i, -c, -o) must be provided."
    usage
fi

echo "Inverter: $inverter"
echo "change: $change"
echo "Option: $option"

# Rest of your script...
